export const DISCOVERY_LOADING = 'DISCOVERY_LOADING';

export const DISCOVERY_SUCCESS = 'DISCOVERY_SUCCESS';

export const DISCOVERY_UPDATE = 'DISCOVERY_UPDATE';

export const DISCOVERY_FAILD = 'DISCOVERY_FAILD';

export const DISCOVERY_SET_LAST_PAGE = 'DISCOVERY_SET_LAST_PAGE';
